__title__ = ''
__package_name__ = ''
__version__ = '0.0.1'
__description__ = "CLI tool for RSS feeds"
__email__ = "deepak008@live.com"
__author__ = 'PyContributors'
__github__ = 'https://github.com/Py-Contributors/rssfeed'
__pypi__ = 'https://pypi.org/project/movens'
__license__ = 'GNU General Public License v3.0'
